version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis_ai_seo_parser
    networks:
      - AI_SEO
  celery:
    container_name: celery_mpstats
    build:
      context: .
    command: ["celery", "-A", "app.celery_app", "worker", "--loglevel=INFO",
              "--pool=gevent", "--concurrency=1"]
    depends_on:
      - redis
    networks:
      - AI_SEO
  fastapi:
    container_name: ai_seo_parser_api
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]
    ports:
      - "9000:9000"
    depends_on:
      - celery
    networks:
      - AI_SEO
networks:
  AI_SEO:
    external: True
    name: "AI_SEO"